/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toilet.solitaire.design.patterns.vgnshiyer;

import java.io.IOException;

import toilet.solitaire.design.patterns.vgnshiyer.models.Game;

public class App {

    public static void main(String[] args) throws IOException{
        startApp();
    }

    public static void startApp() throws IOException{

        // init facade object
        GameFacade game = new GameFacade();

        /* game sequence */
        while(true){
            game.newGame();
            game.startGame();
            game.selectDifficulty();
            game.shuffleDeck();

            while(true){
                game.displayHand();
                game.verifyHand();
                if(Game.getInstance().gameover == true) break; // end game if it reaches stopping condition
                game.getMoves();
                game.performMove();
            }
            game.end();
        }
    }
}
